### ISSUE TITLE
My input format is slightly different.

### ISSUE THREAD

**Issue by Abigail** [E7-87-83/E7-87-83.github.io#1]
Hi.

Thanks for featuring my solution about the Knights adventure in your blog.

However, I think you misunderstood the input my solution takes -- it does take a list of square as input, but it assumes the first square is the square the knight should start on. For instance, the input for the main challenge is `a8 b1 a2 b2 b3 c4 e6`: the square in the top left where the knight starts, followed by the six treasure squares. (That, or my solution has a horrible bug making it just from a8 to h3 in the first move). 

Regards,

Abigail

**Comment by E7-87-83** [comment]
Hello Abigail! It is my honor to talk to you.

My input file for your program's test cases are something like
a8
b1 a2 b2 b3 c4 e6
As you can read from the reault of comparison, the output is valid and
correct.

The information on my blogpost had been placed like a mess due to the
frequent update when new solution came public or new ideas popped up in my
mind. Like some legacy code. Ooops. Probably this causes misundering. As
this raise concerns or inconvenience, I promise that I will "refactor" it
today.

Best Regards,
Cheok Yin

**Comment by E7-87-83** [comment]
The rewriting is done.

**Comment by E7-87-83** [comment]
Hello @Abigail , the rewriting is done.
